camera_name: "905312112011_right"
image_width: 848
image_height: 800
camera_matrix:
   rows: 3
   cols: 3
   data: [ 2.8971586612342838e+02, 0., 4.3282951572869268e+02, 0.,
       2.8842800650095052e+02, 3.9647983507794498e+02, 0., 0., 1. ]
distortion_coefficients:
   rows: 1
   cols: 4
   data: [ 1.1755170565796828e-03, 2.7439249292868447e-02,
       -3.1282234368493568e-02, 5.7239868467015087e-03 ]
distortion_model: equidistant
rectification_matrix:
   rows: 3
   cols: 3
   data: [ 9.9999049872412404e-01, 1.9012821940872346e-03,
       -3.9227015558338232e-03, -1.8968518482397822e-03,
       9.9999755932917211e-01, 1.1328233598542061e-03,
       3.9248457986937090e-03, -1.1253718128906738e-03,
       9.9999166452712951e-01 ]
projection_matrix:
   rows: 3
   cols: 4
   data: [ 2.8845847407434218e+02, 0., 4.2228301048278809e+02,
       -1.8501290547465036e+01, 0., 2.8845847407434218e+02,
       4.0177149677276611e+02, 0., 0., 0., 1., 0. ]
